### ISSUE TITLE
Is endPosition expected to be `undefined`?

### ISSUE THREAD

**Issue by RReverser** [mulesoft-labs/yaml-ast-parser#13]
![image](https://user-images.githubusercontent.com/557590/27247479-be51203a-52f0-11e7-9c55-7e49d269912e.png)

I've been working on some changes to ASTExplorer and just noticed that some nodes have `endPosition` set to `undefined` which makes highlighting to span to the end of the document.

Is this expected in cases like above?

**Comment by KonstantinSviridov** [comment]
Hi @RReverser 

Could you please post an example YAML code which causes the problem.

**Comment by RReverser** [comment]
@KonstantinSviridov As I said, it's the default example on ASTExplorer - https://astexplorer.net/#/gist/f342bd7037cb398bdfb7fdc8d0a3a83b/2ee00032690012c59e3ee116752d93033322c342.

Source: https://raw.githubusercontent.com/mohsen1/astexplorer/483aa3fb9fa081c107e012390683b3c69cfa328d/src/parsers/yaml/codeExample.txt

**Comment by KonstantinSviridov** [comment]
Thanks!
