### ISSUE TITLE
USAGE

### ISSUE THREAD

**Issue by menduz** [mulesoft-labs/yaml-ast-parser#2]
Hello, I'd like to use this parser on a product here at Mule. Could you provide a structure of generated AST and a little example?

Thanks

**Comment by menduz** [comment]
We will need a way to configure custom tags. Could you provide an example usage for it too?

The destination project is mulesoft-labs/http-bat

**Comment by menduz** [comment]
@petrochenko-pavel-a @sichvoge @ddenisenko

**Comment by sichvoge** [comment]
I'll let the guys now, but as far as I know its based on the [raml-definition-system](https://github.com/raml-org/raml-definition-system)

**Comment by ddenisenko** [comment]
Added short description of the `load` method and the tree to https://github.com/mulesoft-labs/yaml-ast-parser/blob/master/README.md

There is no way of custom tags configuration.

**Comment by menduz** [comment]
Thanks
