### ISSUE TITLE
Positions are are inconstent between load and loadAll methods

### ISSUE THREAD

**Issue by adamvoss** [mulesoft-labs/yaml-ast-parser#25]
Behavior (in the node REPL):

```js
yaml = require('yaml-ast-parser')
const str = 'outer:\n  inner: \n    '
```
```js
yaml.safeLoad(str)
```
>{ startPosition: 0,
  endPosition: 21,
}

```js
docs = []
yaml.safeLoadAll(str, d => docs.push(d))
docs[0]
```
>{ startPosition: 0,
  endPosition: 15,
}

**Expected behavior:**
A document should have the same start and end position regardless of how it was loaded.

**Comment by KonstantinSviridov** [comment]
Thanks for the report, Adam !

The fix will be released with the next release.

Regards,
Konstantin

**Comment by adamvoss** [comment]
Thanks @KonstantinSviridov!

I have started doing some development against the `develop` version with this fix.  Do you have any estimate on when it might release?

**Comment by KonstantinSviridov** [comment]
Hi, Adam

The next realease is going to happen during the nearest two weeks.

**Comment by KonstantinSviridov** [comment]
@adamvoss 
Hi, Adam !

The fix has finally been released.
