### ISSUE TITLE
Mark options parameter optional

### ISSUE THREAD

**Issue by Hirse** [mulesoft-labs/yaml-ast-parser#7]
As the options seem to be optional in [`loadDocument`](https://github.com/mulesoft-labs/yaml-ast-parser/blob/master/src/loader.ts#L1662), can you [mark them as optional](https://www.typescriptlang.org/docs/handbook/functions.html#optional-and-default-parameters), so TypeScript stops complaining if I don't pass an options object?

**Comment by ddenisenko** [comment]
Good idea, thank you.
