### ISSUE TITLE
Doesn't report duplicate mapping keys as an error.

### ISSUE THREAD

**Issue by louh** [mulesoft-labs/yaml-ast-parser#8]
For instance if my YAML file is this:

```
dupeValue: 1
dupeValue: 2
dupeValue: 3
```

The parsed object will have three mappings in it, each with the key of `dupeValue`, and the errors array will be empty. According to the YAML specification, duplicate keys are disallowed.

> JSON's RFC4627 requires that mappings keys merely “SHOULD” be unique, while YAML insists they “MUST” be. Technically, YAML therefore complies with the JSON spec, choosing to treat duplicates as an error. In practice, since JSON is silent on the semantics of such duplicates, the only portable JSON files are those with unique keys, which are therefore valid YAML files.

via http://yaml.org/spec/1.2/spec.html#id2759572

**Comment by ddenisenko** [comment]
Are you reducing YAML parser on its own and avoid RAML parser? Currently this check is on the RAML parser level. I agree it's better to be here.

**Comment by louh** [comment]
I'm not using RAML. Is that necessary for a general purpose YAML file?

**Comment by ddenisenko** [comment]
Fixed. Fix will be published in 0.0.31.

**Comment by sichvoge** [comment]
@louh maybe thats not clear, but that specific module / repo covers a level of YAML parsing that might be very specific to RAML
